### view() and copy() of an array

In [7]:
import numpy as np

#view

arr = np.arange(2,16,2)
print(arr)

v = arr.view()

print("\nID on view: ",id(v))
print("\nOriginal ID: ",id(arr))
#view is used when we need to perform operations on large arrays without the overhead of copying data.

#copy

c = arr.copy()
print("\nCopied array :", c)
#copy is used when the original data should remain unchanged.

[ 2  4  6  8 10 12 14]

ID on view:  140679714982960

Original ID:  140679967352624

Copied array : [ 2  4  6  8 10 12 14]


### different way to copy an array

In [15]:
#using .copy()

arr1 = np.array([[1,2],[3,4]])

arr2 = np.copy(arr1)

print("Original array: \n",arr1)
print("\nCopied array:\n",arr2)

#on applying some modification on original array
arr1[0,0]=33

print("\nOriginal array: \n",arr1)
print("\nCopied array:\n",arr2)

Original array: 
 [[1 2]
 [3 4]]

Copied array:
 [[1 2]
 [3 4]]

Original array: 
 [[33  2]
 [ 3  4]]

Copied array:
 [[1 2]
 [3 4]]


In [16]:
#using direct assignment operator

arr1 = np.array([[1,2],[3,4]])

arr2 = arr1

print("Original array: \n",arr1)
print("\nCopied array:\n",arr2)

#on applying some modification on original array
arr1[0,0]=33

print("\nOriginal array: \n",arr1)
print("\nCopied array:\n",arr2)

Original array: 
 [[1 2]
 [3 4]]

Copied array:
 [[1 2]
 [3 4]]

Original array: 
 [[33  2]
 [ 3  4]]

Copied array:
 [[33  2]
 [ 3  4]]


### appending values at the end of the array

#### using .append()

In [22]:
print("Original array:\n", arr1)

arr2 = np.append(arr1, [11,22])
print("After appeding: \n", arr2)

Original array:
 [[33  2]
 [ 3  4]]
After appeding: 
 [33  2  3  4 11 22]


#### using .concatinate

In [27]:
arr1 = np.array([[22,33],[11,22]])

arr2 = np.array([[2,3]])

arr3 = np.concatenate((arr1, arr2), axis=0)

print("Array after concatenation: \n",arr3)

Array after concatenation: 
 [[22 33]
 [11 22]
 [ 2  3]]


In [33]:
#with different data type

arr1 = np.array([3,4,5])
arr2 = np.array([2.2,4.1])

arr3 = np.concatenate((arr1,arr2))
print(arr3)
print(type(arr3),"\n",arr3.dtype)

[3.  4.  5.  2.2 4.1]
<class 'numpy.ndarray'> 
 float64


### swapping column of an array

In [41]:
import numpy as np

arr = np.arange(9).reshape(3,3)
print("Original array:\n",arr)

arr[:, [0,2]]= arr[:,[2,0]]
#on swapping first column with third column
print("After swapping:\n", arr)

Original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After swapping:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


#### creating function for swapping of column

In [47]:
import numpy as np

def swapColumn (arr,start_col,last_col):
    arr[:,[start_col, last_col]]= arr[:,[last_col, start_col]]

arr = np.arange(2,34,2).reshape(4,4)

print("Original array: \n",arr)

swapColumn(arr,1,2)

print("\nAfter swapping second and third column:\n",arr)

Original array: 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

After swapping second and third column:
 [[ 2  6  4  8]
 [10 14 12 16]
 [18 22 20 24]
 [26 30 28 32]]


### insert new axis on array