### comparing two array

In [24]:
import numpy as np

np.random.seed(1)

arr1 = np.random.randint(10,20, size=(3,3))
arr1[1,1]=15
print("Array 1:\n",arr1)

arr2 = np.random.randint(11,20,size=(3,3))
print("\nArray 2:\n",arr2)

comp = arr1 ==arr2
print("\ncomparision between element of arr1 and arr2 is equal:\n",comp)

comp1 = arr1 >arr2
print("\n arr1 is greater:\n",comp1)

comp2 = arr1<arr2
print("\n arr2 is greater:\n", comp2)

comp3 = arr1>= arr2
print("\narr1 is greater than or equal to arr2:\n",comp3)


Array 1:
 [[15 18 19]
 [15 15 10]
 [11 17 16]]

Array 2:
 [[13 15 16]
 [13 15 13]
 [15 18 18]]

comparision between element of arr1 and arr2 is equal:
 [[False False False]
 [False  True False]
 [False False False]]

 arr1 is greater:
 [[ True  True  True]
 [ True False False]
 [False False False]]

 arr2 is greater:
 [[False False False]
 [False False  True]
 [ True  True  True]]

arr1 is greater than or equal to arr2:
 [[ True  True  True]
 [ True  True False]
 [False False False]]


### unique rows in array

In [1]:
import numpy as np

arr = np.array([[1,2,3,4],
                [33,2,3,4],
                [121,23,33,2]])

print("Original array:\n",arr)

arr1 = np.unique(arr)

print("\nUnique array:\n",arr1)

Original array:
 [[  1   2   3   4]
 [ 33   2   3   4]
 [121  23  33   2]]

Unique array:
 [  1   2   3   4  23  33 121]


### unique rows and unique column

In [8]:
import numpy as np

np.random.seed(3)

arr1 = np.array([[3,2,3,1],
                [1,2,1,2],
                [1,2,1,2]])

print("Original array:\n", arr1)

print("Unique rows:\n", np.unique(arr1, axis=0) )

print("Unique column:\n",np.unique(arr1, axis=1))


Original array:
 [[3 2 3 1]
 [1 2 1 2]
 [1 2 1 2]]
Unique rows:
 [[1 2 1 2]
 [3 2 3 1]]
Unique column:
 [[1 2 3]
 [2 2 1]
 [2 2 1]]


### index of unique element

In [10]:
import numpy as np

np.random.seed(3)

arr1 = np.array([[3,2,3,1],
                [1,2,1,2],
                [1,2,1,2]])

print("Index of unique element:\n", np.unique(arr1, return_index=True))

Index of unique element:
 (array([1, 2, 3]), array([3, 1, 0]))
