### view() and copy() of an array

In [2]:
import numpy as np

#view

arr = np.arange(2,16,2)
print(arr)

v = arr.view()

print("\nID on view: ",id(v))
print("\nOriginal ID: ",id(arr))
#view is used when we need to perform operations on large arrays without the overhead of copying data.

#copy

c = arr.copy()
print("\nCopied array :", c)
#copy is used when the original data should remain unchanged.

[ 2  4  6  8 10 12 14]

ID on view:  139814943726288

Original ID:  139814546375472

Copied array : [ 2  4  6  8 10 12 14]


### different way to copy an array

In [3]:
#using .copy()

arr1 = np.array([[1,2],[3,4]])

arr2 = np.copy(arr1)

print("Original array: \n",arr1)
print("\nCopied array:\n",arr2)

#on applying some modification on original array
arr1[0,0]=33

print("\nOriginal array: \n",arr1)
print("\nCopied array:\n",arr2)

Original array: 
 [[1 2]
 [3 4]]

Copied array:
 [[1 2]
 [3 4]]

Original array: 
 [[33  2]
 [ 3  4]]

Copied array:
 [[1 2]
 [3 4]]


In [4]:
#using direct assignment operator
arr1 = np.array([[1,2],[3,4]])

arr2 = arr1

print("Original array: \n",arr1)
print("\nCopied array:\n",arr2)

#on applying some modification on original array
arr1[0,0]=33

print("\nOriginal array: \n",arr1)
print("\nCopied array:\n",arr2)

Original array: 
 [[1 2]
 [3 4]]

Copied array:
 [[1 2]
 [3 4]]

Original array: 
 [[33  2]
 [ 3  4]]

Copied array:
 [[33  2]
 [ 3  4]]


### appending values at the end of the array

#### using .append()

In [5]:
print("Original array:\n", arr1)

arr2 = np.append(arr1, [11,22])
print("After appeding: \n", arr2)

Original array:
 [[33  2]
 [ 3  4]]
After appeding: 
 [33  2  3  4 11 22]


#### using .concatinate

In [6]:
arr1 = np.array([[22,33],[11,22]])

arr2 = np.array([[2,3]])

arr3 = np.concatenate((arr1, arr2), axis=0)

print("Array after concatenation: \n",arr3)

Array after concatenation: 
 [[22 33]
 [11 22]
 [ 2  3]]


In [7]:
#with different data type

arr1 = np.array([3,4,5])
arr2 = np.array([2.2,4.1])

arr3 = np.concatenate((arr1,arr2))
print(arr3)
print(type(arr3),"\n",arr3.dtype)

[3.  4.  5.  2.2 4.1]
<class 'numpy.ndarray'> 
 float64


### swapping column of an array

In [8]:
import numpy as np

arr = np.arange(9).reshape(3,3)
print("Original array:\n",arr)

arr[:, [0,2]]= arr[:,[2,0]]
#on swapping first column with third column
print("After swapping:\n", arr)

Original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After swapping:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


#### creating function for swapping of column

In [9]:
import numpy as np

def swapColumn (arr,start_col,last_col):
    arr[:,[start_col, last_col]]= arr[:,[last_col, start_col]]

arr = np.arange(2,34,2).reshape(4,4)

print("Original array: \n",arr)

swapColumn(arr,1,2)

print("\nAfter swapping second and third column:\n",arr)

Original array: 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

After swapping second and third column:
 [[ 2  6  4  8]
 [10 14 12 16]
 [18 22 20 24]
 [26 30 28 32]]


### insert new axis on array

In [10]:
import numpy as np

arr = np.arange(2,34,2).reshape(4,4)

print("Initial array:\n", arr)

newArr = arr[np.newaxis]#it just extend the dimension 2D array now becomes the 3D
print("\nAfter increasing axis:\n",newArr)

print("\n", newArr.shape)

Initial array:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

After increasing axis:
 [[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]
  [26 28 30 32]]]

 (1, 4, 4)


### .hstack() & .vstack()

#### .hstack()
<h6> is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.</h6>

In [11]:
import numpy as np

arr1 = np.random.seed(10)
arr1 = np.random.randint(10, 20, size=(3,3))

arr2 = np.random.randint(39, 60, size=(3,2))

print("First array:\n",arr1)
print("\nSecond array:\n", arr2)

newArr = np.hstack((arr1, arr2))

print("\nAfter horizontally stacked:\n", newArr)

First array:
 [[19 14 10]
 [11 19 10]
 [11 18 19]]

Second array:
 [[39 49]
 [47 43]
 [58 55]]

After horizontally stacked:
 [[19 14 10 39 49]
 [11 19 10 47 43]
 [11 18 19 58 55]]


#### .vstack
<h6>is used to stack the sequence of input arrays vertically to make a single array.</h6>

In [12]:
import numpy as np

arr1 = np.random.seed(10)
arr1 = np.random.randint(10, 20, size=(3,3))

arr2 = np.random.randint(39, 60, size=(2,3))

print("First array:\n",arr1)
print("\nSecond array:\n", arr2)

newArr = np.vstack((arr1, arr2))

print("\nAfter vertically stacked:\n", newArr)

First array:
 [[19 14 10]
 [11 19 10]
 [11 18 19]]

Second array:
 [[39 49 47]
 [43 58 55]]

After vertically stacked:
 [[19 14 10]
 [11 19 10]
 [11 18 19]
 [39 49 47]
 [43 58 55]]


### .block
<h6>is used to create nd-arrays from nested blocks of lists.</h6>

In [13]:
import numpy as np

arr = np.random.seed(11)

arr1 = np.random.randint(1,10,size=(2,2))
print("Array 1:\n",arr1)

arr2 = np.random.randint(11,20, size=(2,2))
print("\nArray 2:\n",arr2)

arr3 = np.random.randint(39,50,size=(2,2))
print("\nArray 3:\n",arr3)

reArr = np.block([[arr1],[arr2]])

print("\n", reArr)

Array 1:
 [[1 2]
 [8 2]]

Array 2:
 [[18 13]
 [19 11]]

Array 3:
 [[39 43]
 [41 40]]

 [[ 1  2]
 [ 8  2]
 [18 13]
 [19 11]]


### .dstack
<h6>by using np.dstack(), we can get a combined array in stack index by index </h6>

In [14]:
import numpy as np

arr1 = np.array([2,3,4])
arr2 = np.array([10,20,30])
arr3 = np.array([5,7,33])

newArr = np.dstack((arr1,arr3, arr2))

print("after stacked:\n",newArr)

after stacked:
 [[[ 2  5 10]
  [ 3  7 20]
  [ 4 33 30]]]


### array splitting

#### by np.split()
<h6>it devides array with equal interval </h6>

In [15]:
import numpy as np

arr = np.random.seed(33)

arr1 = np.random.randint(10,20, size=10)
print("Before split: ", arr1)

arr2 = np.split(arr1,5)
print("After splitting: ",arr2)

print(arr2[0])

Before split:  [14 17 18 12 12 19 19 13 16 13]
After splitting:  [array([14, 17]), array([18, 12]), array([12, 19]), array([19, 13]), array([16, 13])]
[14 17]


#### by np.array_split
<h6>it also can split array with uequal interval</h6>

In [16]:
import numpy as np

arr1 = np.arange(1,10)
arr1=arr1.reshape(3,3)
print("Original array:\n",arr1)

arr2 = np.array_split(arr1,2)

print("\nAfter splitting: \n", arr2)

print("\n",arr2[0])

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After splitting: 
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]

 [[1 2 3]
 [4 5 6]]


### also can split horizotally by .hsplit and vertically by .vsplit 

### by using np.dsplit()

In [17]:
import numpy as np 

np.random.seed(10)

arr1 = np.random.randint(10,20,size=16)
arr1 = arr1.reshape(2,2,4)

print("Original array:\n", arr1)

arr2 = np.dsplit(arr1, 2)

print("\nAfter splitting:\n", arr2)

print("\nHorizontally split:\n",np.hsplit(arr1, 2))

print("\nVertically split:\n",np.vsplit(arr1, 2))

Original array:
 [[[19 14 10 11]
  [19 10 11 18]]

 [[19 10 18 16]
  [14 13 10 14]]]

After splitting:
 [array([[[19, 14],
        [19, 10]],

       [[19, 10],
        [14, 13]]]), array([[[10, 11],
        [11, 18]],

       [[18, 16],
        [10, 14]]])]

Horizontally split:
 [array([[[19, 14, 10, 11]],

       [[19, 10, 18, 16]]]), array([[[19, 10, 11, 18]],

       [[14, 13, 10, 14]]])]

Vertically split:
 [array([[[19, 14, 10, 11],
        [19, 10, 11, 18]]]), array([[[19, 10, 18, 16],
        [14, 13, 10, 14]]])]
