### Array initialization

In [1]:
import numpy as np

arr1 = np.array([2,3,4])
print(arr1)

[2 3 4]


In [2]:
#some other method of array creation

#creating array by passing list and change types into float

arr1 = np.array([[1,2],[3,4]], dtype=float)
print(arr1)

#creating array by passing tuples

arr2 = np.array(((1,2),(3,4)), dtype=float)
print(arr2)


#creating 2X3 array with all zeros

arr3= np.zeros((2,3))
print(arr3)

#creating array with constant value and dtype complex

arr4=np.full((2,3), 6, dtype=complex)
print(arr4)



[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


#### np.arange()


In [19]:
#used to generate an array within range with evenly distributed

arr1 = np.arange(20,10,-2)
arr2 = np.arange(10,20,2)
arr3 = np.arange(1,10).reshape(3,3)

print(arr1)
print(arr2)
print(arr3)

[20 18 16 14 12]
[10 12 14 16 18]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### np.linspace()

In [21]:
arr1 = np.linspace(2,9,5)#initialize array from start to end with total number of element
print(arr1)

[2.   3.75 5.5  7.25 9.  ]


### Array indexing

In [3]:
#slicing array

arr = np.array([[2,3,1,5],
               [7,5,8,2],
               [1,2,0,9]])


temp = arr[:2,:3:2]
print(temp)

#boolean array indexing

temp = arr > 3
print(temp)

#array greater than 3
gret = arr[temp]
print("Element greater than 3 are ",gret)

[[2 1]
 [7 8]]
[[False False False  True]
 [ True  True  True False]
 [False False False  True]]
Element greater than 3 are  [5 7 5 8 9]


### Basic operation on array

In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

#adding 1 to every element of a

print("After addition: \n", a+1)

print("Sum of array a and b:\n", a+b)

print("Multiplication: (ans will be different then actual multiplication)\n",a*b)

#matrix multiplication
print("Matrix multiplication: \n", a.dot(b))

After addition: 
 [[2 3]
 [4 5]]
Sum of array a and b:
 [[ 6  8]
 [10 12]]
Multiplication: (ans will be different then actual multiplication)
 [[ 5 12]
 [21 32]]
Matrix multiplication: 
 [[19 22]
 [43 50]]


### Other math operation on array

In [5]:
arr1 = np.array([[2,4,7,8],[5,6,7,9]])

print("Array 1 :\n", arr1)

arr2 = np.array([[55,66,77,22],[66,55,77,88]])

sum = arr1+arr2
#sum = np.add(arr1, arr2)
print("Sum of arr1 and arr2\n",sum)

sqrt = np.sqrt(sum)
print("\nSquare root of sum \n", sqrt)

trasposeOfArray = np.transpose(arr1)

print("Transpose of array 1: \n", trasposeOfArray)

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
 
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

Array 1 :
 [[2 4 7 8]
 [5 6 7 9]]
Sum of arr1 and arr2
 [[57 70 84 30]
 [71 61 84 97]]

Square root of sum 
 [[7.54983444 8.36660027 9.16515139 5.47722558]
 [8.42614977 7.81024968 9.16515139 9.8488578 ]]
Transpose of array 1: 
 [[2 5]
 [4 6]
 [7 7]
 [8 9]]
Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


### Basic array characteristics

In [6]:
arr = np.array([[1,2],
               [3,4]])

#dimesion of array
print("Dimension of array: ", arr.ndim)

#shape of array
print("Shape of array:", arr.shape)

#type of array
print("Type of array is: ", type(arr))

#type of element of an array
print("Type of element:", arr.dtype)



Dimension of array:  2
Shape of array: (2, 2)
Type of array is:  <class 'numpy.ndarray'>
Type of element: int64
