## Linear algebra in Numpy

###  rank, trace, determinant, inverse and raised to power

In [9]:
import numpy as np

arr = np.array([[2,3,4],
                [11,2,3],
                [55,44,33]])

#rank of matrix
print("Rank of arr: ", np.linalg.matrix_rank(arr))

#trace of matrix
print("\nTrace of matrix:", np.trace(arr))#sum of diagonal element

#determinant of matrix
print("\nDeterminant of matrix: ", np.linalg.det(arr))

#inverse of matrix
print("\nInverse of arr: ", np.linalg.inv(arr))

#raised to power
print("\nCube of arr: \n",np.linalg.matrix_power(arr,3))

Rank of arr:  3

Trace of matrix: 37

Determinant of matrix:  770.0000000000003

Inverse of arr:  [[-0.08571429  0.1         0.0012987 ]
 [-0.25714286 -0.2         0.04935065]
 [ 0.48571429  0.1        -0.03766234]]

Cube of arr: 
 [[ 10777   7703   6509]
 [ 10472   7521   6260]
 [102828  74041  62304]]


#### matrix eigen value

In [22]:
import numpy as np

arr = np.array([[2,3,4],
                [11,2,3],
                [55,44,33]])

print("Original array:\n",arr)

a = np.linalg.eigh(arr)

print("\nEigen values of arr:",a)

Original array:
 [[ 2  3  4]
 [11  2  3]
 [55 44 33]]

Eigen values of arr: EighResult(eigenvalues=array([-48.37787268,  -8.67199659,  94.04986927]), eigenvectors=array([[ 0.61854062,  0.60467256, -0.50177544],
       [ 0.43592085, -0.79537931, -0.42112321],
       [-0.65374346,  0.04174744, -0.75556379]]))


### Matrix and vector product

In [5]:
import numpy as np

vector_a = 2 + 3j
vector_b = 4 + 1j

print("Dot product between vector a and vrctor b: ", np.dot(vector_a, vector_b))
print("VDot product between vector a and vrctor b: ", np.vdot(vector_a, vector_b))

Dot product between vector a and vrctor b:  (5+14j)
VDot product between vector a and vrctor b:  (11-10j)


#### Solving linear equation

#### np.lingalg.solve(a,b)
<h6> Solve a system of linear scalar equations.Computes the “exact” solution, x, of the well-determined, i.e., full rank, linear matrix equation ax = b.

In [7]:
import numpy as np

a = np.array([[1,1],[1,2]])

b = np.array([4,6])
#x+y=4
#x+2y=6

print("Solution of linear equations: ", np.linalg.solve(a,b))

Solution of linear equations:  [2. 2.]


#### np.lingalg.lstsq(A.T, a)
<h6>Return the least-squares solution to a linear matrix equation.Solves the equation a x = b by computing a vector x that minimizes the Euclidean 2-norm || b – a x ||^2. The equation may be under-, well-, or over- determined (i.e., the number of linearly independent rows of a can be less than, equal to, or greater than its number of linearly independent columns). If a is square and of full rank, then x (but for round-off error) is the “exact” solution of the equation.

In [8]:

 import numpy as np
import matplotlib.pyplot as plt
 
# x co-ordinates
x = np.arange(0, 9)
A = np.array([x, np.ones(9)])
 
# linearly generated sequence
y = [19, 20, 20.5, 21.5, 22, 23, 23, 25.5, 24]
# obtaining the parameters of regression line
w = np.linalg.lstsq(A.T, y)[0] 
 
# plotting the line
line = w[0]*x + w[1] # regression line
plt.plot(x, line, 'r-')
plt.plot(x, y, 'o')
plt.show()

ModuleNotFoundError: No module named 'matplotlib'