### mathematics operation in matrix

#### basic operations

In [7]:
import numpy as np

arr1 = np.array([[1,2],[5,6]])

arr2 = np.array([[3,4],[4,7]])

print("Element wise addition:\n", arr1+arr2)

print("\nElement wise subtraction\n", arr2-arr1)

print("\nElement wise division:\n", arr1/arr2)

print("\nElement wise multiplication:\n", arr1*arr2)

print("\nActual multiplication:\n", arr1.dot(arr2))

Element wise addition:
 [[ 4  6]
 [ 9 13]]

Element wise subtraction
 [[ 2  2]
 [-1  1]]

Element wise division:
 [[0.33333333 0.5       ]
 [1.25       0.85714286]]

Element wise multiplication:
 [[ 3  8]
 [20 42]]

Actual multiplication:
 [[11 18]
 [39 62]]


#### advanced operation

In [15]:
import numpy as np

arr1 = np.array([[1,2],[5,6]])


print("Sqrt of each element of array:\n", np.sqrt(arr1))

print("\nTotal sum of horizontal axis: ", np.sum(arr1, axis=1))

print("\nTotal sum of vertical axis: ", np.sum(arr1, axis=0))

print("\nTotal sum of element:",np.sum(arr1))

print("\nTranspose of given array:\n",np.transpose(arr1))

Sqrt of each element of array:
 [[1.         1.41421356]
 [2.23606798 2.44948974]]

Total sum of horizontal axis:  [ 3 11]

Total sum of vertical axis:  [6 8]

Total sum of element: 14

Transpose of given array:
 [[1 5]
 [2 6]]
