### Binary operations

In [3]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([2,4,5])

# np.bitwise_and()
print("Bitwise and of each element of two array:\n", np.bitwise_and(arr1, arr2))

#np.bitwise_or()
print("Bitwise_or of each element of two array:\n", np.bitwise_or(arr1, arr2))

#np.bitwise_xor()
print("Bitwise xor of each element of two array:\n", np.bitwise_xor(arr1, arr2))

print("Bitwise invert:", np.invert(arr1))

Bitwise and of each element of two array:
 [0 0 1]
Bitwise_or of each element of two array:
 [3 6 7]
Bitwise xor of each element of two array:
 [3 6 6]
Bitwise invert: [-2 -3 -4]


#### biwise right shift

In [9]:
import numpy as np

arr1 = 11
shift = 2

print("Array: ", arr1, "Shift: ", shift)

print("After shift: ", np.right_shift(arr1, shift))

Array:  11 Shift:  2
After shift:  2


#### binary represantation

In [16]:
import numpy as np

num = 22
arr1 = np.array([1,2,3,4])

print("Binary representation: ",np.binary_repr(num, width=None))

np.binary_repr(arr1[3])

Binary representation:  10110


'100'

#### packbits

In [21]:
import numpy as np
arr1 = np.array([[1,0,0],
                  [1,1,1],
                  [0,0,1]])

arr2 = np.packbits(arr1,axis= None)
arr2

array([[128],
       [224],
       [ 32]], dtype=uint8)

#### unpackbits

In [3]:
import numpy as np

arr1 = np.array([[128],
                 [224],
                 [32]], dtype="uint8")



arr2= np.unpackbits(arr1, axis=1)
arr2

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=uint8)