### Binary operations

In [3]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([2,4,5])

# np.bitwise_and()
print("Bitwise and of each element of two array:\n", np.bitwise_and(arr1, arr2))

#np.bitwise_or()
print("Bitwise_or of each element of two array:\n", np.bitwise_or(arr1, arr2))

#np.bitwise_xor()
print("Bitwise xor of each element of two array:\n", np.bitwise_xor(arr1, arr2))

print("Bitwise invert:", np.invert(arr1))

Bitwise and of each element of two array:
 [0 0 1]
Bitwise_or of each element of two array:
 [3 6 7]
Bitwise xor of each element of two array:
 [3 6 6]
Bitwise invert: [-2 -3 -4]


#### biwise right shift

In [9]:
import numpy as np

arr1 = 11
shift = 2

print("Array: ", arr1, "Shift: ", shift)

print("After shift: ", np.right_shift(arr1, shift))

Array:  11 Shift:  2
After shift:  2


#### binary represantation

In [16]:
import numpy as np

num = 22
arr1 = np.array([1,2,3,4])

print("Binary representation: ",np.binary_repr(num, width=None))

np.binary_repr(arr1[3])

Binary representation:  10110


'100'

#### packbits

In [21]:
import numpy as np
arr1 = np.array([[1,0,0],
                  [1,1,1],
                  [0,0,1]])

arr2 = np.packbits(arr1,axis= None)
arr2

array([[128],
       [224],
       [ 32]], dtype=uint8)

#### unpackbits

In [3]:
import numpy as np

arr1 = np.array([[128],
                 [224],
                 [32]], dtype="uint8")



arr2= np.unpackbits(arr1, axis=1)
arr2

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=uint8)

### Mathematical function

#### sin/cos/tan function

In [5]:
import numpy as np
import math as m

arr = [0, np.pi/3, m.pi/2, m.pi]

print("Original list: ",arr)

sin_values= np.sin(arr)
print("Sine of arr: ", sin_values)

Original list:  [0, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]
Sine of arr:  [0.00000000e+00 8.66025404e-01 1.00000000e+00 1.22464680e-16]


#### hyperbolic function sinh/cosh/tanh

In [6]:
import numpy as np

arr = [10,30,50]

sinh_value= np.sinh(arr)

print("Original list: ", arr)

print("sinh values: ", sin_values)

Original list:  [10, 30, 50]
sinh values:  [0.00000000e+00 8.66025404e-01 1.00000000e+00 1.22464680e-16]


#### functions for rounding numpy.around(), numpy.round(), numpy.rint(), fix\floor\ceil\trunc

In [10]:
import numpy as np

arr = [10.54,30.32,50.11]
rounded = np.round(arr)


print("Original list: ", arr)

print("Rounded values: ",rounded )



Original list:  [10.54, 30.32, 50.11]
Rounded values:  [11. 30. 50.]


### string operations

#### np.lower(), np.split(), np.join(),.....

In [8]:
import numpy as np

str1 = "Hello world i am here to help you"

str_split = np.char.split(str1, " ")
s_upper = np.char.upper(str1)
s_lower = np.char.lower(s_upper)
print(str_split)
print(s_upper)
print(s_lower)

['Hello', 'world', 'i', 'am', 'here', 'to', 'help', 'you']
HELLO WORLD I AM HERE TO HELP YOU
hello world i am here to help you


#### np.char.join()

In [10]:
import numpy as np
 

print(np.char.join('-', 'Hello'))
 

print(np.char.join(['-', ':'], ['Hello', 'World']))

H-e-l-l-o
['H-e-l-l-o' 'W:o:r:l:d']


#### np.char.count(), np.char.rfind()

In [32]:
import numpy as np



str1 = "Hello world i am here to help you"

split_str = np.char.split(str1)

list_str = split_str.item()

arr_str = np.array(list_str)

print(arr_str)

print(np.char.rfind(arr_str,"el"))

np.char.count(arr_str,"el")



['Hello' 'world' 'i' 'am' 'here' 'to' 'help' 'you']
[ 1 -1 -1 -1 -1 -1  1 -1]


array([1, 0, 0, 0, 0, 0, 1, 0])

#### there is some otherfunctions like isnumeric(), islower(), isupper(),...

#### string comparision

In [40]:
import numpy as np

print("College is equal to college:", np.equal("college", "College"))

print("College is greater than college:", np.greater("college", "College"))

print("College is not equal to success:", np.not_equal("College", "success"))

College is equal to college: False
College is greater than college: True
College is not equal to success: True
