### Searching in numpy array

#### <ul><li>numpy.where()</li><li>numpy.searchsorted()</li></ul>

In [5]:
import numpy  as np 

arr1 = np.array([[1,2,3],
                 [33,4,5],
                 [6,5,4]])

arr2 = np.array([1,2,33,4,5,6])

print("Index of 33: ",np.where(arr1==33))
print("Index of 33: ",np.where(arr2==33))

Index of 33:  (array([1]), array([0]))
Index of 33:  (array([2]),)


In [11]:
import numpy  as np 


arr2 = np.array([1,2,33,4,5,6])

print("Index of 33: ",np.searchsorted(arr2,33, side="left"))

Index of 33:  6


### array sorting

#### np.sort()

In [5]:
import numpy as np

arr1 = np.array([[33,22,44],
                 [11,55,66],
                 [33,6,7]])

print("Original arry:\n",arr1)

print("\nSorted array:\n", np.sort(arr1, axis=0))

Original arry:
 [[33 22 44]
 [11 55 66]
 [33  6  7]]

Sorted array:
 [[11  6  7]
 [33 22 44]
 [33 55 66]]


#### np.argsort()
<h6>It returns the indices that would sort an array.

In [1]:
import numpy as np

arr1 = np.array([[33,22,44],
                 [11,55,66],
                 [33,6,7]])
print("Original array:\n",arr1)

print("Indices that sort an array:\n", np.argsort(arr1))

print()

Original array:
 [[33 22 44]
 [11 55 66]
 [33  6  7]]
Indices that sort an array:
 [[1 0 2]
 [0 1 2]
 [1 2 0]]
