### Creating a white image

In [4]:
import numpy as np
import cv2
array_created = np.full((500, 500, 3), 
                        255, dtype = np.uint8) 
  
# displaying the image 
cv2.imshow("image", array_created)

<class 'numpy.ndarray'>
(737280,)
(1024, 720)
[[  0   1   2 ... 205 206 207]
 [208 209 210 ... 157 158 159]
 [160 161 162 ... 109 110 111]
 ...
 [144 145 146 ...  93  94  95]
 [ 96  97  98 ...  45  46  47]
 [ 48  49  50 ... 253 254 255]]


: 