#### Different operations on array

#### In 1D array

In [2]:
import numpy as np
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [6]:
arr=arr*2

In [7]:
arr

array([2, 4, 6, 8])

In [9]:
arr = arr **2
arr

array([ 4, 16, 36, 64])

### Note:
In numpy array divide by zero gives infinity and not any error


In [10]:
arr=arr/0
arr

C:\Users\thapa\AppData\Local\Temp\ipykernel_8692\2844148512.py:1: RuntimeWarning: divide by zero encountered in divide
  arr=arr/0


array([inf, inf, inf, inf])

In [11]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6,7])
arr2-arr1

array([3, 3, 3, 3])

#### In 2D array

In [13]:
arr1 = arr1.reshape(2,2)
arr2 = arr2.reshape(2,2)

In [14]:
arr1/arr2

array([[0.25      , 0.4       ],
       [0.5       , 0.57142857]])

In [15]:
arr1*arr2

array([[ 4, 10],
       [18, 28]])

###
<u><i>But in real array multiplication result will be different since here only element to element multiplication is performed.

In [16]:
#To obtain the real multiplication result we do following operation
arr1.dot(arr2)

array([[16, 19],
       [36, 43]])