### <u> Reshaping Data </u>

In [16]:
# one dimension to other dimension
import numpy as np
arr = np.random.randint(1,50,12)
arr
#will print 12 random numbers
print(arr.shape)
#will print(12,)
#converting it to two dimensional aray
arr = arr.reshape(2,6)
print(arr)
print("After reshaping = ",arr.ndim)
print(arr.reshape(4,3))

#two dimension to one dimension

arr=arr.reshape(12)
print(arr)

(12,)
[[10 36  5 10 32 13]
 [20 47  5 12 43 17]]
After reshaping =  2
[[10 36  5]
 [10 32 13]
 [20 47  5]
 [12 43 17]]
[10 36  5 10 32 13 20 47  5 12 43 17]


In [21]:
#arr.ndim -> number of dimension
#1 dimension to three dimension and vice versa

import numpy as np
arr=np.random.randint(1,100,12)
arr=arr.reshape(2,2,3)
print(arr)
print(f"Number of dimension: {arr.ndim}")

[[[45 16 36]
  [46 27 69]]

 [[ 4 43 29]
  [63 91 14]]]
Number of dimension: 3


In [26]:
# if we give number of rows but dont know about number of column then
import numpy as np
arr = np.random.randint(1,100,12)
arr1 = arr.reshape(2,-1)
#here -1 is given to calculate number of column by program itself
print(arr1)
#similarly if we have number of column but don't have number of rows then
print(" ")
arr2 = arr.reshape(-1,2)
print(arr2)

[[ 1  8 66  4 52 94]
 [33 36 39 68 45 40]]
 
[[ 1  8]
 [66  4]
 [52 94]
 [33 36]
 [39 68]
 [45 40]]
