#### <u> Slicing 2D array </u>

In [15]:
import numpy as np
a= np.array([[1,2,3],[3,4,5],[2,6,1]])
a[1,2]

5

In [16]:
a[:2]

array([[1, 2, 3],
       [3, 4, 5]])

In [17]:
a[:2,:2]

array([[1, 2],
       [3, 4]])

In [21]:
arr=np.random.seed(108)
arr=np.random.randint(1,500,30).reshape(6,5)
arr

array([[100, 280, 146, 460, 367],
       [343,  83, 117, 307, 490],
       [ 54, 391, 375, 350, 394],
       [365, 322, 499,   5, 359],
       [ 24, 127, 337,  77, 477],
       [440, 393, 176, 447, 380]])

In [23]:
arr[2:,:3]

array([[ 54, 391, 375],
       [365, 322, 499],
       [ 24, 127, 337],
       [440, 393, 176]])