###  More array functions

In [1]:
import numpy as np
np.random.seed(10)
arr=np.random.randint(1,21,10)
arr

array([10,  5, 16,  1, 18, 17, 18,  9, 10,  1])

In [41]:
np.random.shuffle(arr)#shuffles the array elements
arr

array([ 1, 10, 18, 16, 18, 10, 17,  1,  9,  5])

In [47]:
np.unique(arr)#displays unique nummber of the array

array([ 1,  5,  9, 10, 16, 17, 18])

In [49]:
np.unique(arr).size#counts the unique count of elements

7

In [52]:
arr

array([ 1, 10, 18, 16, 18, 10, 17,  1,  9,  5])

In [53]:
np.unique(arr, return_index = True, return_counts= True)#returns three arra: 1.The array with unique values 2.The array with respective index values 3.The array with counting frequency


(array([ 1,  5,  9, 10, 16, 17, 18]),
 array([0, 9, 8, 1, 3, 6, 2], dtype=int64),
 array([2, 1, 1, 2, 1, 1, 2], dtype=int64))