### 2D Array with fixed datatype

In [1]:
import numpy as np
np.random.seed(20)
arr = np.random.randint(1,21,9).reshape(3,3)
arr

array([[ 4, 16, 10],
       [12,  8,  3],
       [ 1,  9, 20]])

In [2]:
np.min(arr,axis=1)

array([4, 3, 1])

In [3]:
np.max(arr,axis=0)

array([12, 16, 20])

In [4]:
np.cumsum(arr)#cumulative sum 

array([ 4, 20, 30, 42, 50, 53, 54, 63, 83])

In [5]:
np.cumsum(arr, axis=0)

array([[ 4, 16, 10],
       [16, 24, 13],
       [17, 33, 33]])

In [6]:
np.cumsum(arr, axis=1)

array([[ 4, 20, 30],
       [12, 20, 23],
       [ 1, 10, 30]])