In [9]:
import numpy as np
arr = np.arange(1,20)
# print(arr>10)#checks every individual
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
# arr%2==0
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr[arr%2==0]=0
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19])