### Some more functions in numpy

#### In 1D array

In [14]:
import numpy as np
arr = np.array([10,20,30,40,50])
np.min(arr)#returns the minimum number

10

In [2]:
np.max(arr)#returns the max number

50

In [3]:
np.argmin(arr)#returns the position of min number

0

In [4]:
np.argmax(arr)#returns the position of max number

4

In [5]:
np.sqrt(arr)#returns a array which consists sq. root of every number

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [6]:
np.sin(arr)#sin value of every number

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [7]:
np.cos(arr)#cos value of every number

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [10]:
np.linspace(1,2,5)#returns the number with linespace

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
np.sum(arr)#returns the sum of every individual

150

In [13]:
arr.sum()#also returns the sum of every individual

150

#### In 2D array

In [18]:
np.random.seed(12)
mat = np.random.randint(1,30,9).reshape(3,3)
mat

array([[12, 28,  7],
       [18,  3,  4],
       [ 4, 13, 17]])

In [19]:
mat.sum()

106

In [20]:
np.max(mat)

28

In [21]:
np.min(mat)

3