### NumPy Functions

#### <u>zeros</u>  <h5> This function creates an array (either one dimensional or multi dimensional) and fill all the values with zero '0'.<br> For Example: <br> </h5>

In [1]:
import numpy as np
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [6]:
import numpy as np
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

### <u> Ones </u>

In [5]:
import numpy as np
arr = np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### <u> eyes </u>

In [9]:
import numpy as np
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr = np.eye(2,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.]])

In [4]:
import numpy as np
arr=np.diag([2,3,4,5])
arr

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [5]:
import numpy as np
arr = np.diag([2,3,4,5,5])
np.diag(arr)

array([2, 3, 4, 5, 5])

## <u> randint </u>

In [9]:
import numpy as np
arr = np.random.randint(1,10,3)
arr

array([9, 9, 8])

###  <u> rand </u>

In [10]:
import numpy as np
arr= np.random.rand(5)
arr
# rand functions range is automatically set from 0 to 1

array([0.87611542, 0.06304216, 0.01794898, 0.97679074, 0.07467006])

## <u> random.rand with range </u>

In [11]:
import numpy as np 
arr = np.random.rand(2,3)
#it creates the random array of 2 dimension with members from 0 to 1
arr

array([[0.66126994, 0.70082903, 0.32180144],
       [0.65327718, 0.21892927, 0.55232118]])

## <u> randn </u>

In [12]:
import numpy as np
arr = np.random.randn(5)
#it'll generate a random value close to zero. This may return positive or negative as well.
arr

array([ 2.46552362, -0.57312384, -0.51269945, -0.29795568, -0.81168675])