### <u> Stacking 2D array with fixed datatype

In [1]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr2

array([5, 6, 7, 8, 9])

In [4]:
np.hstack((arr1,arr2))#it'll arrange the matrix horizontally

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [5]:
np.vstack((arr1,arr2))#it'll arrange the matrix vertically

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

### next

In [6]:
import numpy as np
np.random.seed(108)
arr1= np.random.randint(1,21,9).reshape(3,3)
arr2 = np.random.randint(50,100,9).reshape(3,3)
np.hstack((arr1,arr2))

array([[ 4, 18, 12, 94, 51, 54],
       [15, 19, 19, 88, 73, 66],
       [10,  7, 10, 62, 78, 58]])

In [7]:
np.vstack((arr1,arr2))

array([[ 4, 18, 12],
       [15, 19, 19],
       [10,  7, 10],
       [94, 51, 54],
       [88, 73, 66],
       [62, 78, 58]])